/**
 * @file   config.h.in
 *
 * @section LICENSE
 *
 * The MIT License
 *
 * @copyright Copyright (c) 2023 TileDB, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @section DESCRIPTION
 *
 * Configuration file including various information about the library,
 * including cmake variables, git information, and other build information.
 * This file is generated by cmake during the build process.
 *
 * @todo Incorporate this information into benchmark logging.
 */

#ifndef TILEDB_CONFIG_H
#define TILEDB_CONFIG_H

constexpr const char SIFT_TEST_DIR[] = "";
constexpr const char CURRENT_DATETIME[] = "2024-03-25 13:50:24";
constexpr const char CMAKE_SOURCE_DIR[] = "/Users/parismorgan/repo/TileDB-Vector-Search-2/src";
constexpr const char BUILD_TYPE[] = "Debug";
constexpr const char CXX_VERSION[] = "15.0.0.15000309";
constexpr const char CXX_COMPILER_ID[] = "AppleClang";
constexpr const char IVF_HACK_CXX_COMPILER[] = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++";
constexpr const char CMAKE_CXX_FLAGS[] = "-Wall -Wno-unused-variable ";
constexpr const char CMAKE_CXX_FLAGS_DEBUG[] = "-g";
constexpr const char CMAKE_CXX_FLAGS_RELEASE[] = "-O3 -DNDEBUG";
constexpr const char CMAKE_CXX_FLAGS_RELWITHDEBINFO[] = "-O2 -g -DNDEBUG";
constexpr const char GIT_REPO_NAME[] = "TileDB-Vector-Search-2";
constexpr const char GIT_REPO_URL[] = "https://github.com/TileDB-Inc/TileDB-Vector-Search.git";
constexpr const char GIT_BRANCH[] = "lums/tmp/graph-search-for-vamana";
constexpr const char GIT_COMMIT_HASH[] = "4259823c";
constexpr const char GIT_COMMIT_DATE[] = "2024-03-25";
constexpr const char GIT_COMMIT_TIME[] = "13:50:00";

#endif  // TILEDB_CONFIG_H
