name: Test Build wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate_backwards_compatability_data:
    name: Generate Backwards Compatibility Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Print Python version
        run: |
          which python
          which pip
          python --version

      - name: Build Indexes
        run: |
          # TODO: test this on a branch with a real tag
          # release_tag=$(git describe --tags --abbrev=0)
          release_tag="0.0.0"
          echo "release_tag" && echo $release_tag
          echo "pwd" && pwd
          echo "ls" && ls
          echo ""
          cd apis/python && pip install . && cd ../..
          echo ""
          echo "pwd" && pwd
          echo "ls" && ls
          echo "pip freeze" && pip freeze
          echo "pwd" && pwd
          echo "ls" && ls
          echo ""
          echo "python backwards-compatability-data/generate_data.py $release_tag" && python backwards-compatability-data/generate_data.py $release_tag
          echo ""
          echo "pwd" && pwd
          echo "ls" && ls
          echo "ls backwards-compatability-data" && ls backwards-compatability-data
          echo "ls backwards-compatability-data/data" && ls backwards-compatability-data/data
          echo "ls backwards-compatability-data/data/0.0.0" && ls backwards-compatability-data/data/0.0.0
          echo ""
          echo "git status" && git status
          echo "git branch" && git branch
          echo "git fetch origin jparismorgan/temp-testing" && git fetch origin jparismorgan/temp-testing
          echo "git checkout jparismorgan/temp-testing" && git checkout jparismorgan/temp-testing
          echo "git status" && git status
          echo "git branch" && git branch
          echo "git add backwards-compatability-data/data/" && git add backwards-compatability-data/data/
          echo "git commit -m '[automated] Update backwards-compatability-data for release $release_tag'" && git commit -m "[automated] Update backwards-compatability-data for release $release_tag"
          echo "git push origin jparismorgan/temp-testing" && git push origin jparismorgan/temp-testing
          echo "git status" && git status

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: generate_backwards_compatability_data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Running!
        run: |
          "Running!"