name: Test Build wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate_backwards_compatability_data:
    name: Generate Backwards Compatibility Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Release Tag
        id: get_release_tag
        run: |
          # TODO: test this on a branch with a real tag
          # release_tag=$(git describe --tags --abbrev=0)
          release_tag="0.0.0"
          echo "release_tag" && echo $release_tag
          echo "::set-output name=release_tag::$release_tag"

      - name: Print Python version
        run: |
          which python
          which pip
          python --version

      - name: Build python
        run: |
          cd apis/python
          pip install .[test]

      - name: List Installed Python Packages
        run: |
          pip freeze

      - name: Build Indexes
        run: |
          echo "pwd" && pwd
          echo "ls" && ls
          echo ${{ steps.get_release_tag.outputs.release_tag }}
          python backwards-compatability-data/generate_data.py ${{ steps.get_release_tag.outputs.release_tag }}

      - name: Commit and Push to Main Branch
        run: |
          echo "git status" && git status
          echo "git branch" && git branch
          echo "git fetch origin main" && git fetch origin main
          echo "git checkout main" && git checkout main
          echo "git status" && git status
          echo "git branch" && git branch

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: generate_backwards_compatability_data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Running!
        run: |
          Running build_wheels