name: Build wheels

on:
  push:
    branches:
      - release-*
      - refs/tags/*
  pull_request:
    branches:
      - '*wheel*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        # `windows-2022, ` blocked by https://github.com/pybind/pybind11/issues/3445#issuecomment-1525500927

    steps:
      - uses: actions/checkout@v3

      - name: 'Brew setup on macOS' # x-ref c8e49ba8f8b9ce
        if: ${{ startsWith(matrix.os, 'macos-') == true }}
        run: |
          set -e pipefail
          brew install automake pkg-config ninja

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_SKIP: "*-win32 cp27-* cp35-* cp36-* cp37-* pp* *_i686 *musllinux*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BUILD_VERBOSITY: 3
          MACOSX_DEPLOYMENT_TARGET: "12.0"
        with:
          package-dir: "apis/python"
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

# TODO: Needs support for pulling in the root directory
#  build_sdist:
#    name: Build source distribution
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build sdist
#        run: pipx run build --sdist
#
#      - uses: actions/upload-artifact@v3
#        with:
#          path: dist/*.tar.gz
