name: Check formatting

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'

jobs:
  # Based on: https://github.com/TileDB-Inc/TileDB-Cloud-Py/blob/main/.github/workflows/tiledb-cloud-py.yaml#L15
  format-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: ".github/workflows/check-formatting.yml"
      - name: Install pre-commit
        run: |
          cd apis/python
          pip install ".[formatting]"
      - name: Restore pre-commit cache
        uses: actions/cache@v3
       with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Pre-commit checks
        run: pre-commit run --all-files --verbose