name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        if: ${{ startsWith(matrix.os, 'ubuntu-') == true }}
        run: sudo apt install libopenblas-dev
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -S ./src -B ./src/build -DCMAKE_BUILD_TYPE=Debug -DTILEDB_VS_ENABLE_BLAS=ON
      - name: Build
        run: cmake --build ./src/build -j3
      - name: Run Tests
        run: cmake --build ./src/build --target check-ci
