name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install libopenblas-dev
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -S ./src -B ./src/build -DCMAKE_BUILD_TYPE=Debug -DTILEDB_VS_ENABLE_BLAS=ON
      - name: Build
        run: cmake --build ./src/build -j3
      - name: Fix Windows dll inclusion with ctest
        if: ${{ runner.os == 'Windows' }}
        run: |
            cp .\src\build\externals\install\bin\tiledb.dll D:/a/TileDB-Vector-Search/TileDB-Vector-Search/src/build/libtiledbvectorsearch/include/test
      - name: Run Tests
        run: cmake --build ./src/build --target check-ci
