name: Python API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        run: sudo apt install libopenblas-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=3.10 numpy`
          environment-name: test-env
          create-args: >-
            python=3.10
            numpy
            tiledb
            tiledb-py
            pybind11
      - name: Build and test python
        run: |
          export TILEDB_DIR=`pwd`/experimental/build/externals/install/lib/cmake/TileDB
          ls $TILEDB_DIR
          export LD_LIBRARY_PATH=`pwd`/experimental/build/externals/install/lib
          cd apis/python
          pip install .
          pytest -k "not ingest" # TODO: requires token
          pip uninstall tiledb.vector_search
          pip install -e .
          pytest -k "not ingest" # TODO: requires token
        shell: bash
