name: Python API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        run: sudo apt install libopenblas-dev
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print Python version
        run: |
          which python
          which pip
          python --version
      - name: Build and test python
        run: |
          pip install .[test]
          cd apis/python
          pytest
          # TODO: fix editable on linux
          #pip uninstall -y tiledb.vector_search
          #pip install -e .
          #pytest
          pip install -r test/ipynb/requirements.txt
          pytest --nbmake test/ipynb
        env:
          TILEDB_REST_TOKEN: ${{ secrets.TILEDB_CLOUD_HELPER_VAR }}
        shell: bash -el {0}
