name: Python API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, ihn/python-api]

jobs:
  Run-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        run: sudo apt install libopenblas-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}      
      - name: Print Python version
        run: |
          which python
          which pip
          python --version
      - name: Install pybind11
        run: pip install "pybind11[global]"
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -S ./experimental -B ./experimental/build -DCMAKE_BUILD_TYPE=Debug -DTILEDB_VS_PYTHON=ON
      - name: Build
        run: cmake --build ./experimental/build
