name: Python API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=3.10 numpy`
          environment-name: test-env
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
          create-args: >-
            python=3.10
            numpy
            tiledb
            tiledb-py
            pybind11
            openblas
      - name: Build and test python
        run: |
          cd apis/python
          pip install .
          pytest -k "not ingest" # TODO: requires token
          pip uninstall tiledb.vector_search
          pip install -e .
          pytest -k "not ingest" # TODO: requires token
        shell: bash
