# Cloned from https://github.com/TileDB-Inc/tiledb-quarto-template

name: Render and deploy Quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenBLAS
        run: sudo apt install libopenblas-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print Python version
        run: |
          which python
          which pip
          python --version
      - name: Install pybind11
        run: pip install "pybind11[global]" "pydantic<2"
      - uses: actions/checkout@v3
      - name: Install
        run: pip install .

      - name: "Install Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Quarto render"
        shell: bash
        run: |
          pip install quartodoc PyYAML click "griffe<0.33" # incompatible
          # create a symlink to the tiledbvcf python package, so it doesn't have to be installed
          #ln -s apis/python/src/tiledb/vector_search
          quartodoc build
          quarto render --fail-if-warnings
          # https://github.com/quarto-dev/quarto-cli/issues/493

      - name: "Deploy to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        # Change to the name of your repo's primary branch name:
        if: github.ref == 'refs/heads/main'
        with:
          # This is GitHub Actions magic; no secrets for us to manage; and this works first-time
          # without any extra configs other than visiting Settings -> Pages in your GitHub repo.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: docs
